spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
     ddl-auto: create #살행 시점에 테이블 다 drop하고 다시 생성하는 것.
    properties:
     hibernate:
       #show_sql: true #systemout 으로 출력
       format_sql: true
       use_sql_comments: true
logging.level:
  org.hibernate.SQL: debug   #sql이 로그로 출력됨
  #org.hibernate.type: trace  #sql문이 남겨질 때 ?가 뭔지 남겨짐